version: "3.12"

services:
  web:
    build: .
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/projecthome30.1
      - static_volume:/projecthome30.1/static
      - media_volume:/projecthome30.1/media
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env

  nginx:
    image: nginx:stable-alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - staticfiles:/usr/share/nginx/html/static
      - media_volume:/media
    depends_on:
      - web

  db:
    image: postgres:16.0
    environment:
      POSTGRES_DB: ${NAME}
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${NAME} -U ${USER}" ]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:7
    volumes:
      - redis_data:/data
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "$REDIS_PASSWORD", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5

  celery:
    build: .
    command: celery -A config worker --loglevel=info
    volumes:
      - .:/drf-spa
    env_file:
      - .env
    depends_on:
      - db
      - redis

  celery_beat:
    build: .
    command: celery -A config beat --loglevel=info
    volumes:
      - .:/drf-spa
    env_file:
      - .env
    depends_on:
      - db
      - redis

networks:
  default:

volumes:
  postgres_data:
  static_volume:
  redis_data:
  media_volume:


#
#version: "3.12"
#
#services:
#  web:
#    build: .
#    command: sh -c "python manage.py runserver 0.0.0.0:8000"
#    volumes:
#      - .:/projecthome30.1
#      - static_volume:/projecthome30.1/static
#      - media_volume:/projecthome30.1/media
#    ports:
#      - "8000:8000"
#    depends_on:
#      - db
#      - redis
#    env_file:
#      - .env
#
#  nginx:
#    build:
#      context: ./nginx
#    ports:
#      - "80:80"
#    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
#      - static_volume:/projecthome30.1/static
#    depends_on:
#      - web
#
#  db:
#    image: postgres:16.0
#    environment:
#      POSTGRES_DB: ${NAME}
#      POSTGRES_USER: ${USER}
#      POSTGRES_PASSWORD: ${PASSWORD}
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready -d ${NAME} -U ${USER}" ]
#      interval: 30s
#      timeout: 10s
#      retries: 5
#
#  redis:
#    image: redis:7
#    volumes:
#      - redis_data:/data
#    env_file:
#      - .env
#    healthcheck:
#      test: [ "CMD", "redis-cli", "-a", "$REDIS_PASSWORD", "ping" ]
#      interval: 30s
#      timeout: 10s
#      retries: 5
#
#  celery:
#    build: .
#    command: celery -A config worker --loglevel=info
#    volumes:
#      - .:/drf-spa
#    env_file:
#      - .env
#    depends_on:
#      - db
#      - redis
#
#  celery_beat:
#    build: .
#    command: celery -A config beat --loglevel=info
#    volumes:
#      - .:/drf-spa
#    env_file:
#      - .env
#    depends_on:
#      - db
#      - redis
#
#networks:
#  default:
#
#volumes:
#  postgres_data:
#  static_volume:
#  redis_data:
#  media_volume: