# Generated by Django 5.2.4 on 2025-08-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0003_subscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
    ]
