# Generated by Django 5.2.4 on 2025-08-19 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_alter_lesson_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='preview',
            field=models.ImageField(blank=True, help_text='Загрузите изображение курса', null=True, upload_to='media/preview', verbose_name='Изображение'),
        ),
    ]
